-- MAPA BÍBLICO — configuração do banco Supabase
create table if not exists public.studies (
  id bigint generated by default as identity primary key,
  title text not null,
  date text not null default 'Data não informada',
  period text not null default 'Patriarcas',
  refs text not null default 'Passagem não informada',
  people jsonb not null default '[]'::jsonb,
  place text not null default 'Não informado',
  context text not null default '',
  reflection text not null default '',
  created_at timestamptz not null default now()
);

alter table public.studies enable row level security;

drop policy if exists "public_read_studies" on public.studies;
create policy "public_read_studies"
on public.studies for select
to anon, authenticated
using (true);

drop policy if exists "public_insert_studies" on public.studies;
create policy "public_insert_studies"
on public.studies for insert
to anon, authenticated
with check (true);

-- Opcional: permitir edição/exclusão futura. Por enquanto deixamos
-- apenas leitura + criação para evitar que alguém apague o trabalho do grupo.
